Template swap fix
18F/ReVAL pull request #29
Opened 2019-04-30 21:27 UTC by cmoscardi

This will fix https://github.com/18F/django-data-ingest/issues/27. I'm not sure about whether it would respect any column swapping that gets done (that's not a piece I fully understand yet in general, but sounds like it's more tied to the API currently)... but it does make sure that whatever ordering gets passed in to the template as the `headers` variable, that ordering remains respected.

As a side effect, it also was easy to fix the error-ing cells not showing up in red by changing to a key-based lookup.

2019-04-30 21:30 UTC, cmoscardi commented
Oh! And I have no idea if that's a good place for the custom template filter, but would defer to you on that @amymok .

2019-04-30 21:44 UTC, amymok requested changes

2019-04-30 21:44 UTC, amymok commented on data_ingest/views.py
> +
For new template tags, you will need to organize them in the `templatetags` folder.  Here's an article on how to structure it: http://blog.appliedinformaticsinc.com/how-to-create-your-own-template-filter-in-django/

2019-05-01 13:00 UTC, tbaxter-18f commented on data_ingest/templates/data_ingest/review-errors.html
> +            {% for h in headers %}
Looking at the views, I'm not seeing where headers is sent to the template. Can you point me in the right direction?

Also, rather than looping through headers and then getting the item for each one, would casting it to an OrderedDict or tuple be an option?

2019-05-01 13:39 UTC, cmoscardi commented on data_ingest/templates/data_ingest/review-errors.html
> +            {% for h in headers %}
Yeah, the templating language is more implicit than I would've expected. It's right here: https://github.com/18F/django-data-ingest/blob/master/data_ingest/views.py#L119

What's going on is that every key in  `data` - a giant dict - becomes a variable you can reference in the template. I had to step through to figure that  out myself, because I didn't immediately see where any of the variables in the template were coming from.

Re: OrderedDict, I agree it'd work as well. Any such approach would involve a bit more preprocessing of the `data` dict on the backend. However, based on what @amymok said [here](https://github.com/18F/django-data-ingest/issues/27#issuecomment-488116845) about potentially renaming columns, it seems to me that passing in a canonical column ordering is a reasonable thing to do (so that preprocessing wouldn't have to respect the same ordering).

2019-05-01 13:46 UTC, tbaxter-18f commented on data_ingest/templates/data_ingest/review-errors.html
> +            {% for h in headers %}
I see what you're saying, and yeah, I think I agree, I'd feel better about it if data was broken down and we were explicit about what we sending over (which would also give a handy point to make it an orderedDict :-) )

2019-05-01 14:06 UTC, cmoscardi commented on data_ingest/views.py
> +
Done!

2019-05-07 17:27 UTC, cmoscardi commented
Hey, are there any other changes you'd like me to make? 

Re: @tbaxter-18f 's point I completely agree but would personally say that's a change for a future PR. If my team and I do end up building out more of a frontend for this, I'd want to switch to jinja2 which does appear to be a [built-in option](https://docs.djangoproject.com/en/2.2/topics/templates/) and is more explicit in the way we discussed (each variable passed in as a kwarg).

2019-05-08 18:35 UTC, amymok commented
Just for more context documenting here:

It looks like the context `data` is actually the output from the validation output.  Here's a bit more documentation on what you would expect to get here.  Right now they are documented in the docstring for `ValidationOutput` class:
https://github.com/18F/django-data-ingest/blob/master/data_ingest/ingestors.py#L142-L155

The original code is looking at the `rows` part:
https://github.com/18F/django-data-ingest/blob/master/data_ingest/ingestors.py#L187

And this is where's the `rows.data` is created and it should be a `dict`:
https://github.com/18F/django-data-ingest/blob/master/data_ingest/ingestors.py#L154

Order may not make sense if the data coming in is JSON, so `OrderedDict` is not a given and may not make sense either.

You should probably change `get_key` to `get_value` because you are getting a value from the key you are given.

Other than that it is good to go!

2019-05-08 18:36 UTC, amymok requested changes

2019-05-08 18:36 UTC, amymok commented on data_ingest/templatetags/get_key.py
> +def get_key(dictionary, key):
`get_value` instead of `get_key` because you are getting the value based on the key

2019-05-08 18:36 UTC, amymok commented on data_ingest/templates/data_ingest/review-errors.html
> +            >{{ row.data | get_key:h }}</td>
Same comment, should be `get_value`

2019-05-15 19:21 UTC, cmoscardi commented on data_ingest/templates/data_ingest/review-errors.html
> +            >{{ row.data | get_key:h }}</td>
Done and done!

2019-05-15 19:22 UTC, cmoscardi commented
OK, that's fixed now. Thanks for the background context as well!

2019-05-15 22:46 UTC, amymok approved these changes

2019-05-15 22:46 UTC, amymok commented
Looks great!  Thank you!

2019-05-15 22:47 UTC, merged