upgrade to django 2.2
18F/ReVAL pull request #78
Opened 2020-01-29 21:20 UTC by cantsin

Fixes https://github.com/18F/ReVAL/issues/20

2020-01-30 19:52 UTC, amymok reviewed
My understanding is that you have tested all the example projects to make sure everything still runs?  If so, can you also add  some texts on that in the PR.

2020-01-30 19:52 UTC, amymok commented on data_ingest/models.py
> +    submitter = models.ForeignKey(User, on_delete=models.CASCADE)
Can you explain why this is necessary?  Same with the two other `on_delete` you added below

2020-01-30 19:52 UTC, amymok commented on data_ingest/tests/test_settings.py
> +MIDDLEWARE = [
Also why do we need these? Was it due to the upgrade?

2020-01-30 19:52 UTC, amymok commented on data_ingest/tests/test_settings.py
> +TEMPLATES = [
Same question.  Why do we need these and was this due to the upgrade?

2020-01-30 20:16 UTC, cantsin commented on data_ingest/models.py
> +    submitter = models.ForeignKey(User, on_delete=models.CASCADE)
Sure thing! As of 2.0, `on_delete` is now a required keyword: 

```
The on_delete argument for ForeignKey and OneToOneField is now required in models and migrations. Consider squashing migrations so that you have fewer of them to update.
```

https://docs.djangoproject.com/en/3.0/releases/2.0/#features-removed-in-2-0

2020-01-30 20:18 UTC, cantsin commented on data_ingest/tests/test_settings.py
> +MIDDLEWARE = [
Yup, required for an update. Previously these would be implicitly set, but now we need to be explicit in what we are including for middleware and templates.

2020-01-30 20:19 UTC, cantsin commented on data_ingest/tests/test_settings.py
> +TEMPLATES = [
Yep, same thing as `MIDDLEWARE`

2020-01-30 20:22 UTC, cantsin commented
> My understanding is that you have tested all the example projects to make sure everything still runs? If so, can you also add some texts on that in the PR.

Yes! I tested all the example projects and ran the tests, let me know if there's something else I might be missing.

2020-01-31 02:07 UTC, amymok approved these changes
Looks good!

2020-01-31 02:09 UTC, amymok requested changes
Can you put those information in the first block of the conversation?  I didn't know that by "resolving conversation", they get collapsed.  It would be great to have those information at the top for anyone else to easily see and understand what were tested, what the changes were.  Thank you!

2020-01-31 17:33 UTC, cantsin commented
> Can you put those information in the first block of the conversation?

Done, thank you.

2020-01-31 17:33 UTC, merged

2020-01-31 18:40 UTC, amymok reviewed
Looks great! You can merge it in! Okay you already did :)